In [1]:
import torch

## probability index

In [10]:
# Probablity defination tensor
probablities = torch.tensor([0.1,0.9])

samples = torch.multinomial(probablities, num_samples=10, replacement=True)
samples

tensor([0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

## concatination 

In [16]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([6])),dim=0)
out

tensor([1, 2, 3, 4, 6])

## triangle lower

In [19]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

triangle upper

In [20]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

## Exponentiating 

In [22]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [23]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

## transposing 

In [26]:
input=torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

## stacking

In [27]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
linear(sample)

tensor([  4.8984, -13.4002,  -2.8542], grad_fn=<SqueezeBackward4>)

## softmax


In [69]:
import torch.nn.functional as F
tensor1 = torch.tensor([1.,2.,3.])
softmax_output = F.softmax(tensor1,dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])