# Playing with torch 

In [1]:
import torch

## Random int tensors

In [9]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 47, -82,  66, -39, -38,  87])

## Nested tesnsors 

In [12]:
tensor = torch.tensor([[0.1,0.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

## Zeros

In [15]:
zeros =torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Ones

In [17]:
ones = torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Empty tensor

In [18]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Arrange

In [19]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

## Lincespace

In [21]:
linespace = torch.linspace(2,5,steps=5)
linespace

tensor([2.0000, 2.7500, 3.5000, 4.2500, 5.0000])

## Logspace 

In [23]:
logspace = torch.logspace(-10,10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

## Identity matrix

In [24]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Empty like 

In [27]:
a= torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])